spring:
  application:
    name: ai-movie-scripts

  # AI Configuration - OpenAI
  ai:
    openai:
      api-key: ${QWEN_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: qwen-plus
          temperature: 0.7


logging:
  level:
    com.liangshou.scripts: info
    org.springframework.ai: info
    org.springframework.jdbc.datasource.DataSourceTransactionManager: DEBUG

# 自定义模型配置
custom-model:
  deepseek:
    api-key: ${DEEPSEEK_API_KEY}
    model: deepseek-chat
    base-url: https://api.deepseek.com
    temperature: 0.7
  qwen:
    api-key: ${QWEN_API_KEY}
    model: qwen-plus
    base-url: https://dashscope.aliyuncs.com/compatible-mode/
    temperature: 0.7
